<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Scada.Comm.Drivers.DrvHttpNotif.Logic</RootNamespace>
    <Version>6.0.0</Version>
    <Authors>Mikhail Shiryaev</Authors>
    <Company>Rapid Software LLC</Company>
    <Product>Rapid SCADA</Product>
    <Copyright>Copyright © 2026</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\ScadaCommon\ScadaCommon\ScadaCommon.csproj" />
    <ProjectReference Include="..\..\..\ScadaCommon\ScadaCommon.Log\ScadaCommon.Log.csproj" />
    <ProjectReference Include="..\..\ScadaComm\ScadaCommCommon\ScadaCommCommon.csproj" />
    <ProjectReference Include="..\AddressBook\AddressBook.csproj" />
  </ItemGroup>

  <Import Project="..\DrvHttpNotif.Shared\DrvHttpNotif.Shared.projitems" Label="Shared" />

</Project>
