<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net10.0</TargetFrameworks>
    <RootNamespace>Scada.Storages.FileStorage</RootNamespace>
    <Version>6.4.0</Version>
    <Authors>Mikhail Shiryaev</Authors>
    <Company>Rapid Software LLC</Company>
    <Product>Rapid SCADA</Product>
    <Copyright>Copyright © 2026</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ScadaCommon\ScadaCommon.csproj" />
  </ItemGroup>

</Project>
