<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0-windows;net10.0-windows</TargetFrameworks>
    <Nullable>disable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <RootNamespace>Scada.Server.Forms</RootNamespace>
    <Version>6.2.3</Version>
    <Authors>Mikhail Shiryaev</Authors>
    <Company>Rapid Software LLC</Company>
    <Product>Rapid SCADA</Product>
    <Copyright>Copyright © 2026</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\ScadaCommon\ScadaCommon\ScadaCommon.csproj" />
    <ProjectReference Include="..\..\..\ScadaCommon\ScadaCommon.Forms\ScadaCommon.Forms.csproj" />
    <ProjectReference Include="..\ScadaServerCommon\ScadaServerCommon.csproj" />
  </ItemGroup>
  
</Project>
