<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Scada.Comm.Drivers.DrvSms.View</RootNamespace>
    <Authors>Mikhail Shiryaev</Authors>
    <Company>Rapid Software LLC</Company>
    <Product>Rapid SCADA</Product>
    <Copyright>Copyright © 2026</Copyright>
    <Version>6.1.0</Version>
    <AssemblyVersion>6.1.0.0</AssemblyVersion>
  </PropertyGroup>

  <Import Project="..\DrvSms.Shared\DrvSms.Shared.projitems" Label="Shared" />

  <ItemGroup>
    <ProjectReference Include="..\..\..\ScadaCommon\ScadaCommon.Log\ScadaCommon.Log.csproj" />
    <ProjectReference Include="..\..\..\ScadaCommon\ScadaCommon\ScadaCommon.csproj" />
    <ProjectReference Include="..\..\ScadaComm\ScadaCommCommon\ScadaCommCommon.csproj" />
    <ProjectReference Include="..\AddressBook.Forms\AddressBook.Forms.csproj" />
    <ProjectReference Include="..\AddressBook\AddressBook.csproj" />
  </ItemGroup>

</Project>
