-- project.app_config definition

-- Drop table

-- DROP TABLE project.app_config;

CREATE TABLE project.app_config (
	file_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	app_id int4 NOT NULL,
	"path" varchar NOT NULL,
	"content" varchar NULL,
	CONSTRAINT app_config_pkey PRIMARY KEY (file_id)
);


-- project.app_config foreign keys

ALTER TABLE project.app_config ADD CONSTRAINT fk_app_config_app FOREIGN KEY (app_id) REFERENCES project.app(app_id);
