-- project.view_file definition

-- Drop table

-- DROP TABLE project.view_file;

CREATE TABLE project.view_file (
	file_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"path" varchar NOT NULL,
	"content" varchar NULL,
	CONSTRAINT view_file_path_un UNIQUE (path),
	CONSTRAINT view_file_pkey PRIMARY KEY (file_id)
);
