-- project.view_file definition

-- Drop table

-- DROP TABLE project.view_file;

CREATE TABLE project.view_file (
	file_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"path" varchar NOT NULL,
	"content" varchar NULL,
	write_time timestamp with time zone,
	CONSTRAINT un_view_file_path UNIQUE (path),
	CONSTRAINT pk_view_file PRIMARY KEY (file_id)
);
