-- project."view" definition

-- Drop table

-- DROP TABLE project."view";

CREATE TABLE project."view" (
	file_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	app_id int4 NOT NULL,
	"path" varchar NOT NULL,
	"content" varchar NULL,
	CONSTRAINT view_pkey PRIMARY KEY (file_id)
);
CREATE UNIQUE INDEX un_view_app_path ON project.view USING btree (app_id, path);


-- project."view" foreign keys

ALTER TABLE project."view" ADD CONSTRAINT view_app_fkey FOREIGN KEY (app_id) REFERENCES project.app(app_id);
